#!/usr/bin/env bash
#Outputs info about your subdomains

subdomains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
subdomain="$2"

dig_cmd ()
{
	subdomain="$2"
	INFO="$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')"
	IP=$(echo "$INFO" | awk '{print $5}')
	RECORD=$(echo "$INFO" | awk '{print $4}')

	echo -e "The subdomain $sub is a $RECORD record and points to $IP"
}

if [ $# -eq 1 ]; then
	for sub in "${subdomains[@]}"; do
		dig_cmd "$domain" "$sub"
	done
elif [ $# -eq 2 ]; then
	dig_cmd "$domain" "$subdomain"
else
	echo "Usage: $0 <domain> <subdomain>"
fi
