#!/usr/bin/env bash

sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=Uc5gBC8W0rk&ab_channel=ComputerKnowledgeBase%28bycobuman%29 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
