#!/usr/bin/env bash
# Install your load balancer

function install() {
	command -v "$1" &> /dev/null

	if [ $? -ne 0 ]; then
		echo -e "	Installing: ${brown}$1${reset}\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
	fi
}

install haproxy

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend th3gr00t-tech-frontend
    bind *:80
    default_backend th3gr00t-tech-backend

backend th3gr00t-tech-backend
    balance roundrobin
    server 422166-web-01 100.26.234.241:80 check
    server 422166-web-02 100.25.135.135:80 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
