#!/usr/bin/env bash
# Iterating 20 times, 4th prints "bad luck from China", 9th "... from Japan", 17th "... from Italy"
i=1
while [ $i -le 20 ]; do
	echo $i
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((i++))
done
