#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
hour=0
minute=0
while [ $hour -le 12 ]; do
	echo Hour: $hour
	while [ $minute -lt 59 ]; do
		((minute++))
		echo $minute
	done
	minute=0
	((hour++))
done
